### ISSUE TITLE
we need  examples at least for mixins

### ISSUE THREAD

**Issue by azabcodes** [mjd-dalloul/flutter-core#1]

**Comment by mjd-dalloul** [comment]
Thanks for bringing this to my attention! I appreciate your interest in my package. I have included an example https://github.com/mjd-dalloul/flutter-core/tree/65fb97414b9336d75aa2e84a700720fb8e4af0ab/example, and I'm planning to add more examples soon. However, I'm a bit short on time at the moment. So I will have to close this issue for now, but please keep an eye out for future updates to my package, which will include more examples. Thanks again for your interest and support!
